WIP - manual merge of lib/rex auth DCERPC
This squashes commits by @meatballs and myself from 2013 which
permit authenticated DCERPC sessions with NTLMv3 SSP signing.

Modules and scripts used for development are not included yet.

This is WIP - there are debug prints, sharp edges, and probable
mistakes here.

-----

Squashed commits from 2013 with retab and change adjustments:

commit 6c0ffd8470ebaba644045eb9784fd97fde6d99a7
Author: RageLtMan <rageltman [at] sempervictus>
Date:   Tue Sep 3 16:08:07 2013 -0400

dcom headers

commit 9a25a5dede587e03dff2740f4bc4b7286c4f74df
Author: RageLtMan <rageltman [at] sempervictus>
Date:   Sat Aug 31 02:43:05 2013 -0400

refactoring

commit f48ada18cfed8f7c737bff2a22139db233af110a (origin/wmis)
Author: RageLtMan <rageltman [at] sempervictus>
Date:   Wed Aug 28 04:07:22 2013 -0400

Resolve alter_context_auth

NTLMSSP negotiation alters instance variables in the Authentication
class. The auth_ntlm_3 method was being called as a class method
by Packet and failing to set nonexistent class variables.

Rewire auth_ntlm_3 as an instance method, call as such from Packet.

Current error: "Exploit failed: ArgumentError bad value for range."
The streak of informative stack traces may be over.

commit dc4936a5e5a23db7d088b348321acd9098fa36df
Author: RageLtMan <rageltman [at] sempervictus>
Date:   Wed Aug 28 03:33:29 2013 -0400

Identify NTLMSSP response properly

DCERPC response is binary, so the comparison between the "substr"
of the raw response and hex string was failing.
Additionally the string used to check the result had the first
byte in last position.

Convert response segment to hex, and compare to the correct
response reference hex string.

Now failing during signing in DCERPC Authentication class with
NoMethodError undefined method `signing_key='

commit 2f2c3810bd8158dacf52ed16815e2d540c6498f7
Author: RageLtMan <rageltman [at] sempervictus>
Date:   Wed Aug 28 03:12:45 2013 -0400

Resolve inability to initiate DCERPC auth session

msf/core/exploit/dcerpc was always setting fake_bind_multi to 1.
This prevented any attempts to initiate the authenticated session.

rex/proto/dcerpc/authentication always expects to receive an auth
type and level, but not all calls made from msf to dcerpc_bind will
be attempting to access dcerpc over TCP with auth. Defaulted
auth_buff generation to use speno/connect when no options are
passed.
Interesting to note that if setting these values in the method
call definition, that passing a NiClass object to the method call
does not result in a value being assigned, but passes the nil to
the array which then gets packed.

At present, wireshark says "DCERPC 451 Bind_ack: call_id: 0,
Fragment: Single, max_xmit: 5840 max_recv: 5840, 1 results:
Acceptance, NTLMSSP_CHALLENGE"

commit aaa945ec957062186dcf730e3dc6a7cf4176d147 (meatballs/wmis)
Merge: 30c1b78893 a8a1bd53f0
Author: Meatballs1 <campbell_ab@hotmail.com>
Date:   Sat Aug 24 03:23:04 2013 -0700

Merge pull request #7 from sempervictus/wmis

Minor typo

commit a8a1bd53f07fe332185f72c9232fae21762cda89
Author: RageLtMan <rageltman [at] sempervictus>
Date:   Mon Aug 5 20:25:06 2013 -0400

fix typo

commit 30c1b78893751e68275ed595b68ec11ac6e4580c
Author: Meatballs <eat_meatballs@hotmail.co.uk>
Date:   Sun Jul 28 21:50:29 2013 +0100

some signing

commit 11eba4661602889bf1d49f87806ca55e3d0ed320
Author: Meatballs <eat_meatballs@hotmail.co.uk>
Date:   Sun Jul 21 00:40:33 2013 +0100

Initial auth comms working

commit 05449c6d88b70ae1f6aebbf234f5372a6f6744cc
Author: Meatballs <eat_meatballs@hotmail.co.uk>
Date:   Sat Jul 20 11:39:11 2013 +0100

Initial commit